name: check MANIFEST.in
on:
  pull_request:
  workflow_dispatch:

jobs:
  check-manifest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v5
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    - name: install check-manifest
      run: |
        python -m pip install --upgrade pip
        python -m pip install check-manifest
    - name: install build dependencies
      run: |
        python -m pip install wheel
    - name: Install yt_xarray
      shell: bash
      run: |
        python -m pip install --no-build-isolation .
    - name: Init submodules
      uses: snickerbockers/submodules-init@v4
    - name: run check-manifest
      run: check-manifest -vvv
