name: Check Build
on: 
  pull_request:
  workflow_dispatch:

jobs:
  twinecheck:
    name: twinecheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install -U build twine
    - name: Build and check source tarball
      run: python -m build
    - name: Twine check
      run: twine check dist/*
