# weekly test, runs mondays at 2:30AM
name: weekly_build

on:
  schedule:
      - cron: "30  2  *  *  1"

jobs:
  test:
    name: ${{ matrix.platform }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10']

    steps:
        - uses: actions/checkout@v4
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        - name: Setup yt_xarray
          run: |
            python -m pip install --upgrade pip
            python -m pip install -e .[full,test]
        - name: List installed deps
          run: pip list
        - name: Run Tests
          run: pytest -v .
